# Generated by Django 4.2.6 on 2023-11-18 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('swift_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='email_to',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='message',
            field=models.TextField(default='Enter your message here'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='title',
            field=models.CharField(default='Title', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='your_email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
