# Generated by Django 4.2.6 on 2023-11-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_transfer', '0002_uploadedfile_created_at_uploadedfile_email_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='email_to',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='message',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='title',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='your_email',
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
