# Generated by Django 4.2.6 on 2023-11-18 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swift_transfer', '0004_uploadedfile_email_to_uploadedfile_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='email_to',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='your_email',
        ),
    ]
