# Generated by Django 4.2.6 on 2023-11-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_transfer', '0005_remove_uploadedfile_email_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='num_anchor_images',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='num_images',
            field=models.IntegerField(default=0),
        ),
    ]
