# Generated by Django 4.2.6 on 2023-11-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swift_transfer', '0007_transfer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
